#!/bin/bash
# WARNING: This file is auto-generated by snipinator. Do not edit directly.
# SOURCE: `rsynccheck/examples/hash-audit_example.sh.jinja2`.

# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -e -x -v -u -o pipefail
set +v



TMP_DIR=$(mktemp -d)
ORIGINAL_PWD="${PWD}"

function delete_tmp_dir {
  cd "${ORIGINAL_PWD}"
  rm -rf "${TMP_DIR}"
}
trap delete_tmp_dir EXIT


################################################################################
mkdir -p "${TMP_DIR}/original"
mkdir -p "${TMP_DIR}/original/subfolder"
mkdir -p "${TMP_DIR}/copy"
################################################################################


dd if=/dev/urandom of="${TMP_DIR}/original/file1" bs=1 count=1
dd if=/dev/urandom of="${TMP_DIR}/original/file2" bs=5 count=1
dd if=/dev/urandom of="${TMP_DIR}/original/file3" bs=1024 count=1
dd if=/dev/urandom of="${TMP_DIR}/original/file4" bs=1024 count=1
dd if=/dev/urandom of="${TMP_DIR}/original/subfolder/file5" bs=1024 count=1
dd if=/dev/urandom of="${TMP_DIR}/original/subfolder/file6" bs=1024 count=1

# Use a small chunk size because our files are small, and we want to demonstrate
# that the completion percentage is approximately correct.
CHUNK_SIZE=10
SRC_DIRECTORY="${TMP_DIR}/original"
DST_DIRECTORY="${TMP_DIR}/copy"

rm -Rf "${DST_DIRECTORY}"
mkdir -p "${DST_DIRECTORY}"

set +x +v
find "${SRC_DIRECTORY}" -type f -name "*" -print0 | while IFS= read -r -d '' PWD_REL_PATH; do
  ABS_PATH=$(realpath "${PWD_REL_PATH}")
  SRC_REL_PATH="${PWD_REL_PATH#${SRC_DIRECTORY}/}"
  SIZE=$(stat --printf="%s" "${ABS_PATH}")
  DST_PATH="${DST_DIRECTORY}/${SRC_REL_PATH}"
  mkdir -p "$(dirname ${DST_PATH})"
  # Copy half the file.
  dd if="${ABS_PATH}" of="${DST_PATH}" bs=1 count=$((SIZE/2)) > /dev/null 2>&1
done
set -x -v

# Generate the audit.yaml file.
python -m rsynccheck.cli \
  hash \
  --ignorefile ".gitignore" \
  --ignoreline .trunk --ignoreline .git \
  --audit-file "${TMP_DIR}/check-changes-audit.yaml" \
  --progress none \
  --chunk-size "${CHUNK_SIZE}" \
  --directory "${SRC_DIRECTORY}"

EXIT_CODE=0
python -m rsynccheck.cli \
  audit \
  --audit-file "${TMP_DIR}/check-changes-audit.yaml" \
  --progress none \
  --output-format table \
  --mismatch-exit 10 \
  --directory "${DST_DIRECTORY}" \
  || EXIT_CODE=$?

if [[ "${EXIT_CODE}" -ne 10 ]]; then
  echo "Expected exit code 10, got ${EXIT_CODE}"
  exit 1
fi

# Now copy all the files correctly.
rm -Rf "${DST_DIRECTORY}"
rsync -a "${SRC_DIRECTORY}/" "${DST_DIRECTORY}"

python -m rsynccheck.cli \
  audit \
  --audit-file "${TMP_DIR}/check-changes-audit.yaml" \
  --progress none \
  --output-format table \
  --mismatch-exit 1 \
  --directory "${DST_DIRECTORY}"
